[package]
name = "halo"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { git = "https://github.com/StefanosChaliasos/halo2", version = "0.2" }
halo2_gadgets = { git = "https://github.com/StefanosChaliasos/halo2", version = "0.2", features = ["unstable"] }
rand = "0.8"
psutil = "3.2.2"
halo_utils = { path = "halo_utils" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.2.7", features = ["derive"] }
hex = "0.4"
criterion = "0.3.5"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "sha256_bench"
path = "src/main.rs"
harness = false

