[package]
name = "halo_utils"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
halo2_proofs = { git = "https://github.com/StefanosChaliasos/halo2", version = "0.2" }
halo2_gadgets = { git = "https://github.com/StefanosChaliasos/halo2", version = "0.2", features = ["unstable"] }
rand = "0.8"
criterion = "0.3.5"
psutil = "3.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.2.7", features = ["derive"] }
